# Generated by Django 4.2.1 on 2023-05-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adm',
            fields=[
                ('id_adm', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_adm', models.CharField(max_length=50)),
                ('apell_adm', models.CharField(max_length=50)),
                ('rol_adm', models.CharField(max_length=50)),
            ],
        ),
    ]
