# Generated by Django 4.2.1 on 2023-05-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('contrasenia_usuario', models.CharField(max_length=9)),
            ],
        ),
    ]
