# Generated by Django 4.2.1 on 2023-05-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0003_cochera'),
    ]

    operations = [
        migrations.AddField(
            model_name='cochera',
            name='img_cochera',
            field=models.CharField(default='', max_length=255),
        ),
    ]
