# Generated by Django 4.2.1 on 2023-05-31 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0006_cochera_descripcion_cochera'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiempoAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.CharField(choices=[('1d', '1 día'), ('15d', '15 días'), ('1m', '1 mes'), ('6m', '6 meses'), ('1a', '1 año')], max_length=10)),
                ('precio', models.IntegerField()),
                ('cochera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend1.cochera')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('servicio1', 'lavado de carroceria'), ('servicio2', 'lavado de carroceria y tapizado'), ('servicio3', 'lavado completo mas tratamiento ceramico')], max_length=10)),
                ('precio', models.IntegerField()),
                ('cochera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend1.cochera')),
            ],
        ),
    ]
