# Generated by Django 4.2.1 on 2023-06-01 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0009_alter_tiempoalquiler_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='cochera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='backend1.cochera'),
        ),
    ]
