# Generated by Django 4.2.1 on 2023-06-07 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0010_alter_servicio_cochera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='cochera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend1.cochera'),
        ),
    ]
