# Generated by Django 4.2.1 on 2023-06-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0011_alter_servicio_cochera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cochera',
            name='capacidad_cochera',
        ),
        migrations.RemoveField(
            model_name='cochera',
            name='ubicacion_cochera',
        ),
    ]
