# Generated by Django 4.2.1 on 2023-06-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0012_remove_cochera_capacidad_cochera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aceptar_terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_usuario',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo_usuario',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono_usuario',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(default='', max_length=50),
        ),
    ]
