# Generated by Django 4.2.1 on 2023-06-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0013_usuario_aceptar_terminos_usuario_apellido_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='', max_length=13),
        ),
    ]
